version: '3'

volumes: 
    pg_django:
    
services: 
    web:
        build: .
        command: python /code/{{project_name}}/manage.py runserver 0.0.0.0:8000
        ports: 
            - "8000:8000"
        volumes:
            - .:/code
        depends_on: 
            - db

    db:
        image: postgres:alpine
        ports:
            - "5432:5432"
        volumes: 
            - pg_django:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            